apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hello-world-gsky
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hello-world-gsky
    app.kubernetes.io/part-of: test-app-ozbp
  name: devfile-sample-hello-world-gsky
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: devfile-sample-hello-world-gsky
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: devfile-sample-hello-world-gsky
    spec:
      containers:
      - image: quay.io/susdas_quay_org/build-e2e-qzfh-tenant/test-app-ozbp/devfile-sample-hello-world-gsky@sha256:876b86c27ac4132a1660f7325fd2350a6b9f792ce30a87cfa626753b7ca98a3d
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
